run:
  deadline: 5m

issues:
  exclude-dirs:
    - test/i18n
    - pkg/test
  exclude-files:
    - pkg/i18n/i18n.go
    - pkg/i18n/translations.go

linters:
  disable-all: true
  enable:
    - errcheck
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    # - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
