kind: CredentialProviderConfig
apiVersion: kubelet.config.k8s.io/v1
providers:
  - name: azure-acr-credential-provider
    apiVersion: credentialprovider.kubelet.k8s.io/v1
    defaultCacheDuration: 10m
    matchImages:
      - "*.azurecr.io"
      - "*.azurecr.cn"
      - "*.azurecr.de"
      - "*.azurecr.us"
      - "*.azsacr.<storageEndpointSuffix>"
    args:
      - <azureJsonFilePath>
