name: Pull Request

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - docs/*

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Install dependencies
        run: make bootstrap
      - name: Check generated code
        run: make ensure-generated
      - name: Run linting rules
        run: make generate test-style
      - name: Build binary
        run: make build-binary
      - name: Check go mod 
        run: make validate-dependencies
      - name: Run unit tests
        run: make test
